/**
 * Staff batch 2 / T5 — NDPR right-of-access subject export (B2-6).
 * Lives in packages/db for the same reason admin-cleanup.ts does: every
 * drizzle-orm call must use the SAME instance as the schema (apps/web has its
 * own copy; mixing instances produces SQL type mismatches).
 *
 * Returns the caller's OWN personal data as a plain JSON-serializable bundle.
 * Excluded by design: passwordHash (never leaves the server), OTPs / magic
 * links / pending tokens (live credentials must not be exportable), and any
 * other user's private rows — inside shared conversations only the subject's
 * OWN messages are returned (counterparty bodies excluded).
 */
import { and, eq, inArray, sql } from "drizzle-orm";
import { getDb } from "./client";
import * as s from "./schema";

export interface SubjectExportBundle {
  exportedAt: string;
  subject: string;
  note: string;
  identity: Record<string, unknown>;
  preferences: unknown[];
  sessions: unknown[];
  authEvents: unknown[];
  vendors: unknown[];
  listings: unknown[];
  reviews: unknown[];
  comments: unknown[];
  messages: unknown[];
  conversationIds: string[];
  notifications: unknown[];
  follows: unknown[];
  wishlist: unknown[];
  likes: unknown[];
  reportsFiled: unknown[];
}

export async function subjectExport(identityId: string): Promise<SubjectExportBundle | null> {
  const db = getDb();
  const me = identityId.trim();
  if (!me) throw new Error("missing_identityId");

  const identityRow = (await db.select().from(s.identities).where(eq(s.identities.id, me)).limit(1))[0];
  if (!identityRow) return null;
  // passwordHash never leaves the server, even to its owner.
  const { passwordHash: _ph, ...identityOut } = identityRow;

  const [
    prefs,
    sessionRows,
    events,
    myVendors,
    myReviews,
    myComments,
    myFollows,
    myWishlist,
    myLikes,
    myReports,
    myNotifications,
  ] = await Promise.all([
    db.select().from(s.userPreferences).where(eq(s.userPreferences.identityId, me)),
    db.select().from(s.sessions).where(eq(s.sessions.identityId, me)),
    db.select().from(s.authEvents).where(eq(s.authEvents.identityId, me)),
    db.select().from(s.vendors).where(eq(s.vendors.identityId, me)),
    db.select().from(s.reviews).where(eq(s.reviews.authorId, me)),
    db.select().from(s.comments).where(eq(s.comments.authorId, me)),
    db.select().from(s.follows).where(eq(s.follows.followerId, me)),
    db.select().from(s.wishlistItems).where(eq(s.wishlistItems.shopperId, me)),
    db.select().from(s.likes).where(eq(s.likes.actorId, me)),
    db.select().from(s.reports).where(eq(s.reports.reporterId, me)),
    db.select().from(s.notifications).where(eq(s.notifications.recipientId, me)),
  ]);

  const vendorIds = myVendors.map((v) => v.id);
  const myListings = vendorIds.length
    ? await db.select().from(s.listings).where(inArray(s.listings.vendorId, vendorIds))
    : [];

  // Conversations I participate in; only MY messages inside them (senderId=me).
  const myConvIds = (
    await db
      .select({ id: s.conversations.id })
      .from(s.conversations)
      .where(sql`participant_ids @> ${JSON.stringify([me])}::jsonb`)
  ).map((r) => r.id);
  const myMessages = myConvIds.length
    ? await db.select().from(s.messages).where(and(inArray(s.messages.conversationId, myConvIds), eq(s.messages.senderId, me)))
    : [];

  return {
    exportedAt: new Date().toISOString(),
    subject: me,
    note: "NDPR right-of-access export generated by Voeq. Contains only data attributed to this account.",
    identity: identityOut as Record<string, unknown>,
    preferences: prefs,
    sessions: sessionRows,
    authEvents: events,
    vendors: myVendors,
    listings: myListings,
    reviews: myReviews,
    comments: myComments,
    messages: myMessages,
    conversationIds: myConvIds,
    notifications: myNotifications,
    follows: myFollows,
    wishlist: myWishlist,
    likes: myLikes,
    reportsFiled: myReports,
  };
}
